version: "3"
services:
  pg:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: asinatra/postgres  
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - /mnt/databases/postgresql/crypto/data:/var/lib/postgresql/data
      - ./docker/postgres/shared/sql:/docker-entrypoint-initdb.d/
      - ./docker/postgres/shared/scripts:/usr/local/share/postgresql/scripts/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto-executor
      POSTGRES_USER: executor
      POSTGRES_PORT: 5432
      
  crypto-datacollect:
    build:
      context: .
      dockerfile: docker/datacollect/Dockerfile
    image: asinatra/datacollect
    depends_on: 
      - pg
    volumes:
      - ./logs/datacollect:/app/logs
    environment:
      host: postgres
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8901:80
    volumes:
      - pgvol:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - pg
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test1234
  
volumes:
  pgvol:

 
